server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;
  add_header X-Content-Type-Options nosniff always;
  location = /health { access_log off; return 200 'ok'; add_header Content-Type text/plain; }
  location ~* \.(js|css|map|png|svg|woff2)$ { try_files $uri =404; }
  location / { try_files $uri $uri/ /index.html; }
}
