import 'reflect-metadata';
import { strict as assert } from 'node:assert';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import type { World } from '@alarmap/map-model';
import { hash } from 'argon2';
import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module.js';
import { Infrastructure } from '../src/infrastructure.js';
import { migrate } from '../src/migrations.js';

test('HTTP : comptes, isolation des mondes, lecture seule, révisions et révocation', async () => {
  const app = await NestFactory.create(AppModule, { logger: false });
  app.setGlobalPrefix('api/v1');
  const infra = app.get(Infrastructure);
  const users = [randomUUID(), randomUUID()];
  const password = 'Mot de passe integration 2026!';
  try {
    await migrate(infra.pool);
    const passwordHash = await hash(password);
    for (const [index, id] of users.entries()) await infra.pool.query('INSERT INTO users(id,email,password_hash,display_name,is_admin) VALUES($1,$2,$3,$4,$5)', [id, `${id}@example.test`, passwordHash, `Test ${index}`, index === 0]);
    await app.listen(0, '127.0.0.1');
    const origin = new URL(infra.config.PUBLIC_APP_URL).origin;
    const base = `${await app.getUrl()}/api/v1`;
    const request = (path: string, token?: string, body?: unknown, method?: string) => fetch(base + path, {
      method: method ?? (body === undefined ? 'GET' : 'POST'),
      headers: { 'Content-Type': 'application/json', Origin: origin, ...(token ? { Authorization: `Bearer ${token}` } : {}) },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    const tokens: string[] = [];
    for (const id of users) {
      const response = await request('/auth/login', undefined, { email: `${id}@example.test`, password });
      assert.equal(response.status, 200);
      assert.match(response.headers.get('set-cookie') ?? '', /HttpOnly/);
      tokens.push((await response.json() as { accessToken: string }).accessToken);
    }
    assert.equal((await request('/worlds')).status, 401);
    assert.equal((await request('/invitations', tokens[1], { email: 'cannot-invite@example.test' })).status, 403);
    const created = await request('/worlds', tokens[0], { name: 'Monde de test privé', radiusKm: 100 });
    assert.equal(created.status, 201);
    const { world } = await created.json() as { world: { id: string; revision: number } };
    assert.deepEqual(await (await request('/worlds', tokens[1])).json(), []);
    assert.equal((await request(`/worlds/${world.id}`, tokens[1])).status, 404);
    const point = { name: 'Lieu de test', longitude: 175, latitude: -20, revision: 0 };
    assert.equal((await request(`/worlds/${world.id}/points`, tokens[1], point)).status, 404);
    await infra.pool.query("INSERT INTO members(world_id,user_id,role) VALUES($1,$2,'viewer')", [world.id, users[1]]);
    assert.equal((await request(`/worlds/${world.id}`, tokens[1])).status, 200);
    assert.equal((await request(`/worlds/${world.id}/points`, tokens[1], point)).status, 403);
    assert.equal((await request(`/worlds/${world.id}/points`, tokens[0], { ...point, latitude: 91 })).status, 400);
    const concurrent = await Promise.all([request(`/worlds/${world.id}/points`, tokens[0], point), request(`/worlds/${world.id}/points`, tokens[0], point)]);
    assert.deepEqual(concurrent.map((response) => response.status).sort(), [201, 409]);
    const reopened = await (await request(`/worlds/${world.id}`, tokens[0])).json() as { world: { revision: number; objects: { id: string; layerId: string; geometry: { coordinates: number[] } }[] } };
    assert.equal(reopened.world.revision, 1);
    assert.equal(reopened.world.objects.length, 1);
    assert.deepEqual(reopened.world.objects[0]?.geometry.coordinates, [175, -20]);
    const pointId = reopened.world.objects[0]!.id;
    const endpoint = '/worlds/' + world.id + '/points/' + pointId;
    const update = { name: 'Lieu renommé', longitude: -179, latitude: 85, revision: 1 };
    assert.equal((await request(endpoint, tokens[1], update, 'PATCH')).status, 403);
    assert.equal((await request(endpoint, tokens[1], { revision: 1 }, 'DELETE')).status, 403);
    assert.equal((await request(endpoint, tokens[0], { ...update, latitude: 100 }, 'PATCH')).status, 400);
    assert.equal((await request(endpoint, tokens[0], { ...update, revision: 0 }, 'PATCH')).status, 409);
    const other = await (await request('/worlds', tokens[0], { name: 'Autre monde', radiusKm: 200 })).json() as { world: { id: string } };
    assert.equal((await request('/worlds/' + other.world.id + '/points/' + pointId, tokens[0], { ...update, revision: 0 }, 'PATCH')).status, 404);
    await infra.pool.query('UPDATE layers SET locked=true WHERE world_id=$1', [world.id]);
    assert.equal((await request(endpoint, tokens[0], update, 'PATCH')).status, 409);
    assert.equal((await request(endpoint, tokens[0], { revision: 1 }, 'DELETE')).status, 409);
    await infra.pool.query('UPDATE layers SET locked=false WHERE world_id=$1', [world.id]);
    const changed = await request(endpoint, tokens[0], update, 'PATCH');
    assert.equal(changed.status, 200);
    const edited = await changed.json() as { world: { revision: number; objects: { id: string; name: string; geometry: { coordinates: number[] } }[] } };
    assert.equal(edited.world.revision, 2);
    assert.equal(edited.world.objects[0]?.id, pointId);
    assert.equal(edited.world.objects[0]?.name, update.name);
    assert.deepEqual(edited.world.objects[0]?.geometry.coordinates, [-179, 85]);
    assert.equal((await request(endpoint, tokens[0], { revision: 1 }, 'DELETE')).status, 409);
    await infra.pool.query("UPDATE members SET role='editor' WHERE world_id=$1 AND user_id=$2", [world.id, users[1]]);
    assert.equal((await request(endpoint, tokens[1], { revision: 2 }, 'DELETE')).status, 200);
    const removed = await (await request('/worlds/' + world.id, tokens[0])).json() as { world: { revision: number; objects: unknown[] } };
    assert.equal(removed.world.revision, 3);
    assert.deepEqual(removed.world.objects, []);
    assert.equal((await request(endpoint, tokens[0], { revision: 3 }, 'DELETE')).status, 404);
    const original = { ...reopened.world.objects[0]!, name: 'Restauré', kind: 'city', style: { color: '#e6b96c', opacity: 1 }, properties: { note: 'Identité conservée' }, startYear: -50, endYear: 100 };
    assert.equal((await request(endpoint, tokens[1], { revision: 2, point: original }, 'PUT')).status, 409);
    await infra.pool.query("UPDATE members SET role='viewer' WHERE world_id=$1 AND user_id=$2", [world.id, users[1]]);
    assert.equal((await request(endpoint, tokens[1], { revision: 3, point: original }, 'PUT')).status, 403);
    const restored = await request(endpoint, tokens[0], { revision: 3, point: original }, 'PUT');
    assert.equal(restored.status, 200);
    const restoredBody = await restored.json() as { world: { objects: unknown[]; revision: number } };
    assert.equal(restoredBody.world.revision, 4);
    assert.deepEqual(restoredBody.world.objects[0], original);
    assert.equal((await request('/worlds/' + other.world.id + '/points/' + pointId, tokens[0], { revision: 0, point: original }, 'PUT')).status, 404);
    await infra.pool.query('UPDATE layers SET locked=true WHERE world_id=$1', [world.id]);
    assert.equal((await request(endpoint, tokens[0], { revision: 4, point: original }, 'PUT')).status, 409);
    await infra.pool.query('UPDATE layers SET locked=false WHERE world_id=$1', [world.id]);
    const rewritten = await request(endpoint, tokens[0], { revision: 4, point: { ...original, name: 'Rétabli' } }, 'PUT');
    assert.equal(rewritten.status, 200);
    assert.equal((await request(endpoint, tokens[0], { revision: 5, point: { ...original, geometry: { type: 'LineString', coordinates: [[0,0],[1,1]] } } }, 'PUT')).status, 400);
    const layersEndpoint = '/worlds/' + world.id + '/layers';
    assert.equal((await request(layersEndpoint, tokens[1], { revision: 5, name: 'Relief' })).status, 403);
    const layerCreated = await request(layersEndpoint, tokens[0], { revision: 5, name: 'Relief' });
    assert.equal(layerCreated.status, 201);
    const withLayer = await layerCreated.json() as { world: World };
    const addedLayer = withLayer.world.layers.find(layer => layer.name === 'Relief')!;
    assert.equal(withLayer.world.revision, 6);
    const layerEndpoint = layersEndpoint + '/' + addedLayer.id;
    const layerUpdate = { name: 'Montagnes', opacity: 0.4, locked: true, revision: 6 };
    assert.equal((await request(layerEndpoint, tokens[1], layerUpdate, 'PATCH')).status, 403);
    assert.equal((await request(layerEndpoint, tokens[0], { ...layerUpdate, opacity: 2 }, 'PATCH')).status, 400);
    const layerChanged = await request(layerEndpoint, tokens[0], layerUpdate, 'PATCH');
    assert.equal(layerChanged.status, 200);
    const changedLayers = await layerChanged.json() as { world: World };
    assert.equal(changedLayers.world.layers.find(layer => layer.id === addedLayer.id)?.opacity, 0.4);
    assert.equal((await request('/worlds/' + world.id + '/points', tokens[0], { ...point, layerId: addedLayer.id, revision: 7 })).status, 409);
    assert.equal((await request(layerEndpoint, tokens[0], { revision: 7 }, 'DELETE')).status, 409);
    assert.equal((await request(layerEndpoint, tokens[0], { ...layerUpdate, locked: false, revision: 7 }, 'PATCH')).status, 200);
    const placed = await request('/worlds/' + world.id + '/points', tokens[0], { ...point, layerId: addedLayer.id, revision: 8 });
    assert.equal(placed.status, 201);
    const placedWorld = await placed.json() as { world: World };
    assert.equal(placedWorld.world.objects.filter(object => object.layerId === addedLayer.id).length, 1);
    assert.equal((await request(layerEndpoint, tokens[0], { revision: 9 }, 'DELETE')).status, 409);
    assert.equal((await request('/worlds/' + other.world.id + '/layers/' + addedLayer.id, tokens[0], { ...layerUpdate, revision: 0 }, 'PATCH')).status, 404);
    const emptyLayer = await (await request(layersEndpoint, tokens[0], { revision: 9, name: 'Vide' })).json() as { world: World };
    const emptyId = emptyLayer.world.layers.find(layer => layer.name === 'Vide')!.id;
    assert.equal((await request(layersEndpoint + '/' + emptyId, tokens[0], { revision: 9 }, 'DELETE')).status, 409);
    assert.equal((await request(layersEndpoint + '/' + emptyId, tokens[0], { revision: 10 }, 'DELETE')).status, 200);
    const otherAccess = await (await request('/worlds/' + other.world.id, tokens[0])).json() as { world: World };
    assert.equal((await request('/worlds/' + other.world.id + '/layers/' + otherAccess.world.layers[0]!.id, tokens[0], { revision: 0 }, 'DELETE')).status, 409);
    assert.equal((await request('/auth/logout', tokens[0], {}, 'POST')).status, 204);
    assert.equal((await request('/worlds', tokens[0])).status, 401);
  } finally {
    await infra.pool.query('DELETE FROM worlds WHERE owner_id=ANY($1::uuid[])', [users]);
    await infra.pool.query('DELETE FROM users WHERE id=ANY($1::uuid[])', [users]);
    await app.close();
  }
});
